### PR TITLE
copy even if formatting or license add fails

### LINKED ISSUE #629: Always generate configs even formatting or validation failed

### PR DESCRIPTION
**Pull request by umairidris**
Fix #629

### CODE REVIEW

**Comment by MartinPetkov** [comment]
Failing gen_check.sh

File: internal/tfengine/tfengine.go [hunk 1]
```diff
@@ -79,23 +80,32 @@ func Run(confPath, outPath string, opts *Options) error {
...
 		if err := licenseutil.AddLicense(tmpDir); err != nil {
-			return fmt.Errorf("add license header: %v", err)
+			errs = append(errs, fmt.Sprintf("add license header: %v", err))
 		}
 	}
 
-	if err := os.MkdirAll(outPath, 0755); err != nil {
-		return fmt.Errorf("failed to mkdir %q: %v", outPath, err)
+	if opts.Format {
+		if err := hcl.FormatDir(&runner.Default{Quiet: true}, tmpDir); err != nil {
```
Comment (MartinPetkov) [inline internal/tfengine/tfengine.go:96]: This seems different from the original intent. Wasn't the idea to format after copying?

Comment (umairidris) [reply internal/tfengine/tfengine.go:96]: Yes, but the issue is when I do that sometimes it starts formatting unexpected files, since --output_path does not need to contain only the files being generated.

Comment (MartinPetkov) [reply internal/tfengine/tfengine.go:96]: Oh, I see. So now it will copy, but surface formatting errors?

Comment (umairidris) [reply internal/tfengine/tfengine.go:96]: Right. It will still exit non-zero to show it isn't successful but the files should all still get moved over

**Review by MartinPetkov — APPROVED** [review]

**Review by xingao267 — APPROVED** [review]
